# Site settings
title: Kulsvier
email: tas@interactify.dk
description: > # this means to ignore newlines until "baseurl:"
    Kulsviergården danner hvert år ramme omkring Nordsjællands største loppemarked, Alsønderup Fester, 1-2 årlige teaterforestillinger, som er arrangeret af vores lokale teaterforening, Kulsvierscenen, adskillige idrætsarrangementer, dansestævner, ugentlige bankospil m.m.
url: "http://kulsviergaarden.dk" # the base hostname & protocol for your site - used for feed.xml
twitter_username: kulsviergaarden
github_username:  interactify

# Build settings
markdown: kramdown


collections:
    faciliteter:
        output: true
        permalink: /faciliteter/:path/
    arrangementer:
        output: true
        permalink: /arrangementer/:path/
    om-os:
        output: true
        permalink: /om-os/:path/
    forside:
        output: true
        permalink: /:path/
