# Site settings
title: Kulsvier
email: tas@interactify.dk
description: > # this means to ignore newlines until "baseurl:"
    Kulsviergården danner hvert år ramme omkring Nordsjællands største loppemarked, Alsønderup Fester, 1-2 årlige teaterforestillinger, som er arrangeret af vores lokale teaterforening, Kulsvierscenen, adskillige idrætsarrangementer, dansestævner, ugentlige bankospil m.m.
url: "http://kulsviergaarden.dk" # the base hostname & protocol for your site - used for feed.xml
twitter_username: kulsviergaarden
github_username:  interactify

# Build settings
markdown: kramdown


collections:
    kontakt:
        output: true
        permalink: /kontakt/:path/
    om-kulsviergaarden:
        output: true
        permalink: /om-kulsviergaarden/:path/
    festlokaler:
        output: true
        permalink: /festlokaler/:path/
    moedeogkonf:
        output: true
        permalink: /moede/:path/
    bankopaakulsviergaarden:
        output: true
        permalink: /banko/:path/
    kulsvierscenen:
        output: true
        permalink: /kulsvierscenen/:path/
    asgi:
        output: true
        permalink: /asgi/:path/
    aktiviteter:
        output: true
        permalink: /aktiviteter/:path/
    loppemarked:
        output: true
        permalink: /loppemarked/:path/
    mad:
        output: true
        permalink: /mad/:path/
    samarbejdspartnere:
        output: true
        permalink: /samarbejdspartnere/:path/
    forside:
        output: true
        permalink: /:path/

