development:
  backend:
    name: netlify-api
    url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: interactify/kulsviergaarden # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit

  - name: "Kontakt" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Kontakt" # Used in the UI, ie.: "New Post"
    folder: "_kontakt" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Om-kulsviergaarden" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Om Kulsviergården" # Used in the UI, ie.: "New Post"
    folder: "_om-kulsviergaarden" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Festlokaler" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Festlokaler" # Used in the UI, ie.: "New Post"
    folder: "_festlokaler" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Moedeogkonferencelokaler" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Møde- & konferencelokaler" # Used in the UI, ie.: "New Post"
    folder: "_moedeogkonf" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Banko-paa-kulsviergaarden" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Banko på Kulsviergården" # Used in the UI, ie.: "New Post"
    folder: "_bankopaakulsviergaarden" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "KulsvierscenenTeater" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Kulsvierscenen" # Used in the UI, ie.: "New Post"
    folder: "_kulsvierscenen" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Idrætsforeningen-ASGI" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Idrætsforeningen ASGI" # Used in the UI, ie.: "New Post"
    folder: "_asgi" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Aktiviteter" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Aktiviteter på gården" # Used in the UI, ie.: "New Post"
    folder: "_aktiviteter" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Loppemarked" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Loppemarked" # Used in the UI, ie.: "New Post"
    folder: "_loppemarked" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Mad" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Mad på Kulsviergaarden" # Used in the UI, ie.: "New Post"
    folder: "_mad" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Samarbejdspartnere" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Samarbejdspartnere" # Used in the UI, ie.: "New Post"
    folder: "_samarbejdspartnere" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image", optional: true}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}

  - name: "Nyheder" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Nyheder" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Billede", name: "content_image", widget: "image", optional: true}
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Nyhed", name: "body", widget: "markdown"}
      - {label: "Kategori", name: "categories", widget: "string"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}

  - name: "Nyhedskasse" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Nyhedskasse" # Used in the UI, ie.: "New Post"
    folder: "_nyhedskasse" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Tekst", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}